### ISSUE TITLE
Is there a way to get the path to an attribute when clicking on it?

### ISSUE THREAD

**Issue by victorbstan** [mohsen1/json-formatter#23]
Hi,

I'm not sure if this functionality is already included or not, but I'm looking to the get the path to an element of the JSON object I'm displaying. When I click on a child attribute, it would be useful for me to get back, perhaps through an `ng-click` directive passing in an `$event`, access to the JSON selector path to specific element, perhaps including the value.

I can imagine perhaps attached to each attribute key, a `data-path` and/or `data-value` with previously mentioned data being accessible from `$event` on click.

Is there something similar to this already or another way I could go about it? 

Thanks!

**Comment by mohsen1** [comment]
Because JSON Formatter is calling itself recursively it's easy to pass down current path and root object to downstream directives. `open` attribute does somehow similar thing. Once you have the root object and path in the directive, you can listen to click events and do whatever you want. I don't think that should be in JSON Formatter itself since JSON Formatter's focus is on rendering a view but feel free to ping me in your fork if you needed help.

**Comment by victorbstan** [comment]
OK, thanks, I'll take a look.
